### ISSUE TITLE
build script output flags not passed to rustdoc

### ISSUE THREAD

**Issue by Eljay** [rust-lang/cargo#1592]
Seems to be the same issue as #1469 

I have a simple build script that just outputs the search path:
```rust
fn main() {
    println!("cargo:rustc-link-search=native=/home/lee/opt/lib");
}
```
This seems to work correctly for building and running normal tests (both inline and in tests/ folder) but the -L flag doesn't get passed to rustdoc.

Example of normal test output vs rustdoc output:
```
Running `rustc tests/version.rs --crate-name version --crate-type bin -g --test -C metadata=0ac5f00c90e58674 -C extra-filename=-0ac5f00c90e58674 --out-dir /home/lee/rust/doctest/target/debug --emit=dep-info,link -L dependency=/home/lee/rust/doctest/target/debug -L dependency=/home/lee/rust/doctest/target/debug/deps --extern doctest=/home/lee/rust/doctest/target/debug/libdoctest.rlib -L native=/home/lee/opt/lib -L native=/home/lee/opt/lib`
```
```
Running `rustdoc --test /home/lee/rust/doctest/src/lib.rs --crate-name doctest -L dependency=/home/lee/rust/doctest/target/debug/deps --extern doctest=/home/lee/rust/doctest/target/debug/libdoctest.rlib`
```
(Also note the search path is added twice to the regular test but I suppose that's a separate issue)

**Comment by alexcrichton** [comment]
Is there a failure mode of this you ran into? Generating documentation shouldn't require linking a library so I don't believe it requires native objects to be available.

**Comment by Eljay** [comment]
It failed to link when compiling the doc tests. I will try to set up a minimal test case.

**Comment by Eljay** [comment]
Ok I think it's only a problem when linking to a shared library. Minimal test project available [here.](https://www.dropbox.com/s/3kofyj4i452wi7w/doctest.tar.gz?dl=0)

Just run build_hello.sh (requires cmake) and then run cargo test.

**Comment by alexcrichton** [comment]
I believe this was fixed in #1530

**Comment by Ogeon** [comment]
It looks like this is still a problem in cargo 0.5.0-nightly (833b947 2015-09-13) on Windows, when depending on rust-openssl. It says that `-lssl32` and `-leay32` can't be found. [Here](https://ci.appveyor.com/project/Ogeon/rustful/build/master-226#L870) is the log from my latest attempt to enable doc-tests on AppVeyor.

**Comment by alexcrichton** [comment]
Can you try using the nightly channel to make sure you're running the most up-to-date Cargo? I'm not sure if this fix was in that Cargo or not.

**Comment by Ogeon** [comment]
Sure, I can give it a try tomorrow. I just thought that it would have propagated to the official builds by now, since it was merged in April.

**Comment by Razican** [comment]
@gkoz sugested [in the forums](https://users.rust-lang.org/t/some-problems-when-packaging-my-interface-with-c/3721) that my problem could be this. It happens in Travis in stable, beta and nightly chanels.

**Comment by alexcrichton** [comment]
Ah ok, sounds like this is probably still an issue!

**Comment by sgrif** [comment]
Just ran into this trying to get Diesel running on my Windows box. Can confirm it's still an issue.

**Comment by jedbrown** [comment]
It seems this issue was never really fixed, and this has been causing projects to avoid doctests for packages that use FFI to shared libraries simply because it requires testers to set the environment variables manually. I can't tell if it's now intentional that `cargo:rustc-link-search=native=*` not apply to doctests.

I know one strain of advice is that native libraries built in `OUT_DIR` should usually be static, though this offloads complexity when that library may have transitive dependencies linked using RPATH.
