### ISSUE TITLE
Unknown platform error under FreeBSD

### ISSUE THREAD

**Issue by dmilith** [rust-lang/cargo#2197]
```
buildhost /tmp/cargo # python -B src/etc/install-deps.py
Traceback (most recent call last):
  File "src/etc/install-deps.py", line 33, in <module>
    raise "Unknown platform"
TypeError: exceptions must be old-style classes or derived from BaseException, not str
zsh: exit 1     python -B src/etc/install-deps.py
```

Are you serious? Isn't python supposed to be cross platform? FreeBSD is far more advanced than most Linuxes these days...

**Comment by alexcrichton** [comment]
Right now Cargo is built Cargo, so what this badly-worded error message is saying is that there is no official snapshot of Cargo for FreeBSD.

Seems like a message we could improve though!

**Comment by JIghtuse** [comment]
Message is fixed. It would be nice to rename this bugreport or to forward it somewhere to have official FreeBSD snaphost one day.

**Comment by dmilith** [comment]
I don't think it's resolved issue. Under my system step "python -B src/etc/install-deps.py" isn't even required to build Cargo without more than one known issue with missing RPATH info in cargo binary #2198. I hacked LD_LIBRARY_PATH problem with wrapper and there's no more issues under FreeBSD. 

Read - FreeBSD is already supported and works just fine. Thanks.

**Comment by dmilith** [comment]
Also, for those who use FreeBSD:

Definition of Rust 1.5.0 for Sofin:
https://github.com/VerKnowSys/sofin-definitions/blob/stable/definitions/rust.def
Binary build:
http://software.verknowsys.com/binary/FreeBSD-11.0-amd64/Rust-1.5.0.txz

Definition includes function "install_cargo" that automatically installs cargo (not available in FreeBSD ports definition yet). Both hacks required to build are also included (line: 19 and wrapper: lines 28-31)

**Comment by alexcrichton** [comment]
@dmilith although FreeBSD may have a snapshot it's not officially supported in the sense that we provide a guarantee that it will continue to work. I'd be fine taking patches to the snapshot download script, but we won't necessarily actively seek them out.
