### ISSUE TITLE
A large chunk of time is spent in phase_4_translate_to_llvm during cargo check

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/cargo#3444]
I was profiling 'cargo check' and it looks like about 53% of the time is spent in phase_4_translate_to_llvm. Is it really necessary to translate_to_llvm during check?

@nrc

**Comment by jrmuizel** [comment]
@nrc

**Comment by nrc** [comment]
This should not be the case (caveat below). Kinda the whole point of `cargo check` is skipping llvm and trans phases. I should double check that we do in fact skip trans and not just llvm, but I'm pretty sure we should. The exception is if there are procedural macros, these must be compiled because they are executed at compile time, but it would be an odd project that spent 53% of time doing that.

I'll look into this...

**Comment by jrmuizel** [comment]
I was profiling cargo check on https://github.com/servo/webrender/tree/master/wrench

**Comment by alexcrichton** [comment]
I think this may be a duplicate of https://github.com/rust-lang/cargo/issues/3418?

**Comment by nrc** [comment]
This should be fixed now.

**Comment by jrmuizel** [comment]
Should the fix be in rustc 1.16.0-nightly (47c8d9fdc 2017-01-08)? Because I'm still seeing the bulk of the time in 44% of time in rustc_driver::driver::phase_4_translate_to_llvm

**Comment by alexcrichton** [comment]
@jrmuizel `cargo check` still generates code for build scripts and such. Out of the 131 invocations of `rustc` in the `wrench` directory 77 of them emit metadata, which means that 54 crates are still compiled. Beyond that though I think this bug is fixed, so closing.

**Comment by jrmuizel** [comment]
I was only profiling the final rustc --crate-name wrench main.rs --crate-type bin --emit=dep-info,metadata invocation so this should be unrelated to build scripts.

**Comment by alexcrichton** [comment]
Ah ok. In that case though this is likely an upstream rustc bug rather than a Cargo bug, as Cargo's just shelling out to rustc with appropriate arguments.

**Comment by jrmuizel** [comment]
Indeed. I've filed https://github.com/rust-lang/rust/issues/38964.
