### ISSUE TITLE
Failing to add owners to crate: 502 bad gateway

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/cargo#4019]
```
$ cargo owner -a github:paritytech:core-devs --verbose`
    Updating registry `https://github.com/rust-lang/crates.io-index`
       Owner adding ["github:paritytech:core-devs"] to crate rlp
error: failed to add owners to crate rlp: failed to get a 200 OK response, got 502
headers:
    HTTP/1.1 100 Continue

    

    HTTP/1.1 502 Bad Gateway

    Connection: keep-alive

    Server: nginx

    Date: Wed, 10 May 2017 11:04:30 GMT

    Content-Type: text/html

    Content-Length: 166

    Via: 1.1 vegur

    

body:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by alexcrichton** [comment]
cc @carols10cents

**Comment by alexcrichton** [comment]
bah didn't mean to close

**Comment by carols10cents** [comment]
This sounds like https://github.com/rust-lang/crates.io/issues/446, this part: 

> It should also be noted that the name of the organization starts with an upper-case letter, but running the cargo owner --add command with a lower-case organization results in a different error

Is there any chance that the `paritytech:core-devs` team is a renamed "owners" team or a legacy admin team? More info: 

* https://help.github.com/articles/converting-your-previous-owners-team-to-the-improved-organization-permissions/
* https://help.github.com/articles/migrating-your-previous-admin-teams-to-the-improved-organization-permissions/

If it is, could you try the workaround in that issue of doing `cargo owner -a github:paritytech:owners` instead and let me know if that works?

If you [create a new access token](https://github.com/settings/tokens/new) with `read:org` scope, and then run this with `[token]` replaced with your token value:

```
curl -u rphmeier:[token]  https://api.github.com/orgs/paritytech/teams
```

do you see the core-devs team? Is `core-devs` the slug for that team?

If you grab the ID for the core-devs team and then run:

```
curl -u rphmeier:[token]  https://api.github.com/teams/[team-id]/membership/rphmeier
```

is the `state` of your membership `active`?

I'm not sure exactly what the problem is if these responses look ok... a few other things I'd want to look into:

* Are there more than 100 teams in this organization?
* Is the github account you're using with crates.io definitely a member of this team?

The code looks like it should be reporting more informative error messages, so once we figure out what the problem is, we'll work on making the error better, but I'm not sure where to start right now...

**Comment by rphmeier** [comment]
Thanks for the detailed response @carols10cents.

> It should also be noted that the name of the organization starts with an upper-case letter, but running the cargo owner --add command with a lower-case organization results in a different error

This was at one point `ethcore:core-devs` but the github organization has been renamed, which could be a big part of the problem.

> do you see the core-devs team? Is core-devs the slug for that team?
yes, but the command 
`curl -u rphmeier:[token]  https://api.github.com/teams/[team-id]/membership/rphmeier`
fails with 

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

which seems like it is the same error crates.io must be encountering.

**Comment by carols10cents** [comment]
> This was at one point ethcore:core-devs but the github organization has been renamed, which could be a big part of the problem.

ooooooooooooooooh. that's helpful. let me try to reproduce.

**Comment by carols10cents** [comment]
aha, yep, found this in the logs searching for rlp:

> 500: duplicate key value violates unique constraint "teams_github_id_key" duplicate key value violates unique constraint "teams_github_id_key" 

looks like we're looking up teams by name, then if we don't find it, trying to insert, but the team github ID stays the same. We should be doing an upsert instead, I'll work on a fix soon.

**Comment by rphmeier** [comment]
Awesome, I'll try again once that patch is deployed.

**Comment by carols10cents** [comment]
@rphmeier I've deployed the patch-- please try again and let me know how it goes!

**Comment by rphmeier** [comment]
All good, thanks.

**Comment by rphmeier** [comment]
This is happening again, can we reopen? Organization name is still the same though.

**Comment by carols10cents** [comment]
Yep, logs look similar. Reopening and investigating.

**Comment by carols10cents** [comment]
@rphmeier can you confirm that the command you're running is still `cargo owner -a github:paritytech:core-devs`?

**Comment by rphmeier** [comment]
I ran it as `cargo owner -a github:paritytech:core-devs --verbose` exactly and it worked.
Before I ran with `ParityTech` and it failed. I didn't think capitalization would matter that much

**Comment by carols10cents** [comment]
Aha!!! Whew, thought I was losing it there for a bit :)

Ok, since this is a different *cause*, I'm going to re-close this issue. I've filed https://github.com/rust-lang/crates.io/issues/1167 to change crates.io to not care about case.

Thank you and sorry about the continued trouble!
