### ISSUE TITLE
cargo plugin sub commands no longer work in nightly version

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang/cargo#5212]
All subcommands that come from external crates stopped working with the latest nightly cargo.

rustc --version
rustc 1.26.0-nightly (a04b88d19 2018-03-19)
rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
cargo --version
cargo 1.26.0-nightly (d6c3983fe 2018-03-16)

```console
Installing /home/travis/.cargo/bin/cargo-make
The command "cargo install --debug cargo-make" exited with 0.
0.04s$ cargo make ci-flow
error: Found argument 'ci-flow' which wasn't expected, or isn't valid in this context
USAGE:
    cargo [SUBCOMMAND]
For more information try --help
```

See build example: https://travis-ci.org/sagiegurari/cargo-make/jobs/355826819#L530

**Comment by matklad** [comment]
Yep, that's a known issue that I've broken **all** subcommands on nightly :-( 

The issue is already fixed in Cargo, the PR with Cargo update to rust-lang/rust is https://github.com/rust-lang/rust/pull/49182

**Comment by anp** [comment]
Looks like https://github.com/rust-lang/rust/pull/49182 merged a couple of days ago, although I'm not sure which nightly it'll ride -- with `nightly-2018-03-21` from rustup I'm seeing `cargo 1.26.0-nightly (d6c3983fe 2018-03-16)`.

**Comment by sagiegurari** [comment]
@matklad when can we expect a fix for this? I tried the latest nightly and its still failing.

**Comment by ehuss** [comment]
@sagiegurari It looks like a new nightly has been pushed with the update to cargo.

**Comment by sagiegurari** [comment]
Thanks @ehuss you are right. Works great now.
