### ISSUE TITLE
building crate w/C library using custom, dynamically linked clang fails

### ISSUE THREAD

**Issue by mykmelez** [rust-lang/cargo#6764]
**Problem**

Building a Rust crate containing a C library using a custom, dynamically-linked clang specified via the `CC` environment variable fails on macOS with a "symbol not found" error, apparently because the system loads libLLVM.dylib from the Rustup-installed toolchain rather than the custom installation:

>cargo:warning=dyld: lazy symbol binding failed: Symbol not found: __ZN4llvm9DIBuilder17createCompileUnitEjPNS_6DIFileENS_9StringRefEbS3_jS3_NS_13DICompileUnit17DebugEmissionKindEybbb
>cargo:warning=  Referenced from: /Users/myk/rust-c-library-testcase/clang/bin/clang-7
>cargo:warning=  Expected in: /Users/myk/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libLLVM.dylib

**Steps**
1. Clone testcase repo: 
    `git clone https://github.com/mykmelez/rust-c-library-testcase.git && cd rust-c-library-testcase`
2. Install custom, dynamically-linked clang:
    `curl -O https://taskcluster-artifacts.net/I36Um3guQMyU-HWz_tnG0Q/0/public/build/clang.tar.xz && tar xf clang.tar.xz`
3. Build crate with custom clang: 
    `CC=clang/bin/clang cargo build`

**Notes**

Output of `cargo version`: cargo 1.33.0 (f099fe94b 2019-02-12)

This appears to have regressed between Rust nightly build 2019-01-06 and 2019-01-07 ([68fe5182c...b92552d55](https://github.com/rust-lang/rust/compare/68fe5182c...b92552d55)):

>\> cargo clean && CC=clang/bin/clang cargo +nightly-2019-01-06 build
>   Compiling cc v1.0.31
>   Compiling rust-c-library-testcase v0.1.0 (/Users/myk/rust-c-library-testcase)
>    Finished dev [unoptimized + debuginfo] target(s) in 1.93s
>\> cargo clean && CC=clang/bin/clang cargo +nightly-2019-01-07 build
>   Compiling cc v1.0.31
>   Compiling rust-c-library-testcase v0.1.0 (/Users/myk/rust-c-library-testcase)
>error: failed to run custom build command for `rust-c-library-testcase v0.1.0 (/Users/myk/rust-c-library-testcase)`
>process didn't exit successfully: `/Users/myk/rust-c-library-testcase/target/debug/build/rust-c-library-testcase-166e0d070d05f6f9/build-script-build` (exit code: 101)

See https://bugzilla.mozilla.org/show_bug.cgi?id=1536486 for an example of the issue in a project that uses a custom, dynamically-linked clang when building for Android targets.

**Comment by ehuss** [comment]
It's a long shot, but I'm curious, have you tried the latest nightly?  There was a similar issue (https://github.com/rust-lang/rust/issues/59034#event-2208295373) that was fixed a couple days ago (https://github.com/rust-lang/rust/pull/59173).

**Comment by mykmelez** [comment]
> It's a long shot, but I'm curious, have you tried the latest nightly? There was a similar issue ([rust-lang/rust#59034 (comment)](https://github.com/rust-lang/rust/issues/59034#event-2208295373)) that was fixed a couple days ago ([rust-lang/rust#59173](https://github.com/rust-lang/rust/pull/59173)).

Thanks for the tip! I updated to the latest nightly and can still reproduce the issue there:

>\> rustup update
>…
>  stable-x86_64-apple-darwin unchanged - rustc 1.33.0 (2aa4c46cf 2019-02-28)
>      beta-x86_64-apple-darwin updated - rustc 1.34.0-beta.3 (7473869a6 2019-03-16)
>   nightly-x86_64-apple-darwin updated - rustc 1.35.0-nightly (0f88167f8 2019-03-18)
>
>\> CC=clang/bin/clang cargo +nightly build
>   Compiling cc v1.0.31
>   Compiling rust-c-library-testcase v0.1.0 (/Users/myk/rust-c-library-testcase)
>error: failed to run custom build command for `rust-c-library-testcase v0.1.0 (/Users/myk/rust-c-library-testcase)`
>process didn't exit successfully: `/Users/myk/rust-c-library-testcase/target/debug/build/rust-c-library-testcase-4d3b681e42b21f8a/>build-script-build` (exit code: 101)

**Comment by mykmelez** [comment]
2019-01-06 only has one copy of libLLVM.dylib, while 2019-01-07 has two:

>\> find ~/.rustup/toolchains/nightly-2019-01-0[67]-x86_64-apple-darwin -name libLLVM.dylib
/Users/myk/.rustup/toolchains/nightly-2019-01-06-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib
/Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib
/Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/libLLVM.dylib

The two are identical (and not hard or soft links):

>\> diff /Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib /Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/libLLVM.dylib
>\> ls -lad /Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib /Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/libLLVM.dylib
-rw-r--r--  1 myk  staff  58531716 Mar 19 14:04 /Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/libLLVM.dylib
-rw-r--r--  1 myk  staff  58531716 Mar 19 14:04 /Users/myk/.rustup/toolchains/nightly-2019-01-07-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib

**Comment by emilio** [comment]
Yeah, see https://github.com/rust-lang/rust/issues/55737. Apparently the LLVM doesn't append the provided suffix on OSX.
