### ISSUE TITLE
Config build.rustc-wrapper is unused.

### ISSUE THREAD

**Issue by OllieBerzs** [rust-lang/cargo#7745]
**Problem**

I added `build.rustc-wrapper = "sccache"` to use the `sccache` in my builds, but when running any cargo command, it says that  `build.rustc-wrapper` is an unused key. 
I found the key in The Cargo Book (https://doc.rust-lang.org/cargo/guide/build-cache.html).

**Steps**

1. Install sccache `cargo install sccache`
2. Add `build.rustc-wrapper = "sccache"` to Cargo config ($CARGO_HOME/config)
3. Run `cargo build` in any project

**Notes**

Output of `cargo version`: cargo 1.40.0 (bc8e4c8be 2019-11-22)

Rust version: 1.40.0
OS: Windows 10

**Comment by ehuss** [comment]
Thanks, this has already been fixed via #7575

**Comment by lebensterben** [comment]
Hi, I still see the error message on `cargo 1.44.0-nightly`.

**Comment by ehuss** [comment]
> Hi, I still see the error message on `cargo 1.44.0-nightly`.

Can you show a sample config file that reproduces the issue and the text of the warning?  I can't seem to reproduce it.

**Comment by lebensterben** [comment]
@ehuss 
I installed `sccache` with `cargo install sccache`, and have these contents in my `~/.cargo/config` file:

```toml
[build]
rustc_wrapper = "sccache"

[expand]
theme = "Monokai Extended Origin"
```

where `sccache` is in the `$PATH`, I've also tried setting it to it's absolute path.

Then, when I run `cargo build`, `cargo test`, or `cargo clippy`, I always see the unused config key in `build.rustc_wrapper` warning.

**Comment by ehuss** [comment]
It should be `rustc-wrapper` with a dash, not an underscore.

**Comment by lebensterben** [comment]
>It should be `rustc-wrapper` with a dash, not an underscore.

@ehuss You're right! Thanks.
